name: Prebuild
on:
  workflow_dispatch:
jobs:
  linux:
    runs-on: beefcake-linux-x64
    name: linux
    steps:
      - run: |
          if [ ! -d "depot_tools" ]; then
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
          fi
          mkdir -p chromium
      - run: |
          gclient config --name src/prebuilds --unmanaged https://github.com/${{ github.repository }}.git
        working-directory: chromium
      - run: |
          gclient sync -D
          if [ ! -d "buildtools" ]; then
            ln -s src/buildtools buildtools
          fi
        working-directory: chromium
      - run: |
          ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
          ./build/linux/sysroot_scripts/install-sysroot.py --arch=x64
        working-directory: chromium/src
      - run: |
          git apply --directory src src/prebuilds/patches/*.patch
          git apply --directory src/v8 src/prebuilds/patches/v8/*.patch
        working-directory: chromium
      - run: |
          gn gen out/linux-arm64/v8 --args="import(\"//prebuilds/v8.gni\") import(\"//prebuilds/mode/release.gni\") import(\"//prebuilds/target/linux-arm64.gni\")"
        working-directory: chromium/src
      - run: |
          ninja -C out/linux-arm64/v8 prebuilds
        working-directory: chromium/src
